spring.application.name=SecureApp

spring.datasource.url=jdbc:postgresql://localhost:5432/employee-management
spring.datasource.username=postgres
spring.datasource.password=password

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always


